// src/components/MenuBar/MenuBar.tsx
import {
  Avatar,
  Box,
  Divider,
  List,
  ListDivider,
  ListItem,
  ListItemButton,
  ListItemContent,
  ListItemDecorator,
  Menu,
  MenuItem,
  Sheet,
  Typography,
  useColorScheme,
} from "@mui/joy";
import Image from "next/image";
import { useMemo, useState } from "react";
import MenuButton from "./MenuButton/MenuButton";

type MenuBarProps = {};

export default function MenuBar({}: MenuBarProps) {
  const [activeMenuIndx, setActiveMenuIndx] = useState<number | null>(null);
  const { mode, setMode } = useColorScheme();

  const menuItems = useMemo(
    () => [
      {
        label: "File",
        items: [
          {
            label: "New File",
            shortcut: "Ctrl+N",
            onClick: () => {},
          },
          {
            label: "New Window",
            shortcut: "Ctrl+Shift+N",
            onClick: () => {},
          },
          {
            label: "Open File",
            shortcut: "Ctrl+O",
            onClick: () => {},
          },
          {
            label: "Save File",
            shortcut: "Ctrl+S",
            onClick: () => {},
          },
          null,
          {
            label: "Exit",
            shortcut: null,
            onClick: () => {},
          },
        ],
      },
      {
        label: "Edit",
        items: [
          {
            label: "Undo",
            shortcut: "Ctrl+Z",
            onClick: () => {},
          },
          {
            label: "Redo",
            shortcut: "Ctrl+Y",
            onClick: () => {},
          },
          null,
          {
            label: "Cut",
            shortcut: "Ctrl+X",
            onClick: () => {},
          },
          {
            label: "Copy",
            shortcut: "Ctrl+C",
            onClick: () => {},
          },
          {
            label: "Paste",
            shortcut: "Ctrl+V",
            onClick: () => {},
          },
          {
            label: "Delete",
            shortcut: "Del",
            onClick: () => {},
          },
          null,
          {
            label: "Find",
            shortcut: "Ctrl+F",
            onClick: () => {},
          },
          {
            label: "Find Next",
            shortcut: "F3",
            onClick: () => {},
          },
          {
            label: "Replace",
            shortcut: "Ctrl+H",
            onClick: () => {},
          },
          {
            label: "Go To",
            shortcut: "Ctrl+G",
            onClick: () => {},
          },
          null,
          {
            label: "Select All",
            shortcut: "Ctrl+A",
            onClick: () => {},
          },
          {
            label: "Time/Date",
            shortcut: "F5",
            onClick: () => {},
          },
        ],
      },
      {
        label: "View",
        items: [
          {
            label: "Zoom In",
            shortcut: "Ctrl+Plus",
            onClick: () => {},
          },
          {
            label: "Zoom Out",
            shortcut: "Ctrl+Minus",
            onClick: () => {},
          },
          {
            label: "Reset Zoom",
            shortcut: "Ctrl+0",
            onClick: () => {},
          },
          null,
          {
            label: "Toggle Full Screen",
            shortcut: "F11",
            onClick: () => {},
          },
          null,
          {
            label: "Toggle Title Bar",
            shortcut: null,
            onClick: () => {},
          },
          null,
          {
            label: "Toggle Theme",
            shortcut: null,
            onClick: () => setMode(mode === "dark" ? "light" : "dark"),
          },
        ],
      },
      {
        label: "About",
        items: [
          {
            label: "About Us",
            shortcut: null,
            onClick: () => {},
          },
          {
            label: "Send Feedback",
            shortcut: null,
            onClick: () => {},
          },
          {
            label: "Report a Problem",
            shortcut: null,
            onClick: () => {},
          },
        ],
      },
    ],
    [mode, setMode]
  );

  return (
    <Sheet sx={{ height: "2.5rem", position: "sticky", top: 0, left: 0 }}>
      <List size="sm" orientation="horizontal">
        <ListItem>
          {menuItems.map(({ items, label }, menuIndx) => (
            <MenuButton
              key={menuIndx}
              onOpen={() => setActiveMenuIndx(menuIndx)}
              onClose={() => setActiveMenuIndx(null)}
              open={activeMenuIndx === menuIndx}
              onHoverOpen={typeof activeMenuIndx === "number"}
              menu={
                <Menu size="sm" sx={{ minWidth: "11rem" }}>
                  {items.map((item, itemIndx) =>
                    item ? (
                      <MenuItem key={itemIndx} onClick={item.onClick}>
                        {item.label}{" "}
                        {item.shortcut && (
                          <Typography
                            fontSize=".6rem"
                            sx={{ marginLeft: "auto" }}
                            variant="outlined"
                            color="info"
                          >
                            {item.shortcut}
                          </Typography>
                        )}
                      </MenuItem>
                    ) : (
                      <ListDivider key={itemIndx} />
                    )
                  )}
                </Menu>
              }
            >
              {label}
            </MenuButton>
          ))}
        </ListItem>
      </List>
    </Sheet>
  );
}

// src/lib/components/MenuBar.svelte
<script lang="ts">
  import * as Menubar from '@/components/ui/menubar';
  import { toggleMode } from 'mode-watcher';
  import EditorTitle from './EditorTitle.svelte';
  import { editors } from '@/store/store';
  import { fade } from 'svelte/transition';
  import { Notpad } from '@/helpers/notpad';
  import { isTauri } from '$lib';

  interface MenuItems {
    label: string;
    items: Item[];
  }

  interface Item {
    label?: string;
    shortcut?: string;
    type?: string;
    onClick?: () => void;
  }

  const menuItems: MenuItems[] = [
    {
      label: 'File',
      items: [
        {
          label: 'New',
          shortcut: isTauri ? 'Ctrl+N' : 'Ctrl+Alt+N',
          onClick: Notpad.editors.createNew
        },

        { label: 'Open...', shortcut: 'Ctrl+O', onClick: Notpad.file.open },
        {
          label: 'Save',
          shortcut: 'Ctrl+S',
          onClick: Notpad.file.save
        },
        { label: 'Save as...', onClick: () => Notpad.file.save({ saveAs: true }) },

        { type: 'separator' },
        { label: 'Print', shortcut: 'Ctrl+P' },
        { type: 'separator' },
        { label: 'Exit' }
      ]
    },
    {
      label: 'Edit',
      items: [
        { label: 'Undo', shortcut: 'Ctrl+Z' },
        { label: 'Redo', shortcut: 'Ctrl+Y' },
        { type: 'separator' },
        { label: 'Cut', shortcut: 'Ctrl+X' },
        { label: 'Copy', shortcut: 'Ctrl+C' },
        { label: 'Paste', shortcut: 'Ctrl+V' },
        { type: 'separator' },
        { label: 'Select All', shortcut: 'Ctrl+A' },
        { label: 'Time/Date', shortcut: 'F5' },
        { type: 'separator' },
        { label: 'Font' }
      ]
    },
    {
      label: 'Search',
      items: [
        { label: 'Find', shortcut: 'Ctrl+F' },
        { label: 'Find Next', shortcut: 'F3' },
        { label: 'Find Previous', shortcut: 'Shift+F3' },
        { label: 'Replace', shortcut: 'Ctrl+H' },
        { label: 'Go To', shortcut: 'Ctrl+G' }
      ]
    },
    {
      label: 'View',
      items: [
        { label: 'Zoom In', shortcut: 'Ctrl+Plus' },
        { label: 'Zoom Out', shortcut: 'Ctrl+Minus' },
        { label: 'Reset Zoom', shortcut: 'Ctrl+0' },
        { type: 'separator' },
        { label: 'Full Screen', shortcut: 'F11' },
        { label: 'Dark Mode', onClick: toggleMode }
      ]
    },
    {
      label: 'Help',
      items: [{ label: 'About Notpad' }]
    }
  ];

  let innerWidth = window.innerWidth;

  $: isXS = innerWidth <= 450;
  $: tabsMode = $editors.length > 1; // compact mode will not available on mobile width (w<=450), also on pc when multiple editors.
  $: singleEditor = $editors.at(0)!;
</script>

<svelte:window bind:innerWidth />

<Menubar.Root class="relative z-10 rounded-sm">
  {#each menuItems as { label, items }}
    <Menubar.Menu>
      <Menubar.Trigger>{label}</Menubar.Trigger>
      <Menubar.Content>
        {#each items as { label, shortcut, type, onClick }}
          {#if type === 'separator'}
            <Menubar.Separator />
          {:else}
            <Menubar.Item on:click={onClick}>
              {label}
              {#if shortcut}
                <Menubar.Shortcut>{shortcut}</Menubar.Shortcut>
              {/if}
            </Menubar.Item>
          {/if}
        {/each}
      </Menubar.Content>
    </Menubar.Menu>
  {/each}

  {#if !isXS && !tabsMode}
    <div
      transition:fade
      class="max-md:!ml-auto md:absolute md:left-1/2 md:top-1/2 md:-translate-x-1/2 md:-translate-y-1/2"
    >
      <EditorTitle editor={singleEditor} />
    </div>
  {/if}
</Menubar.Root>
